language: clojure
jdk:
  - oraclejdk8
# check that it compiles && run linters && run tests
# stop if any of them fails
#script: lein do clean, compile, check, eastwood '{:exclude-namespaces [service.conjectures.specs]}', test
script:
  - lein clean
  - lein compile
  - lein check
  - lein prod-build
  - yarn install
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then yarn appr; fi'
