language: clojure
jdk:
  - oraclejdk8

node_js: "8"
install: yarn install

script:
  - lein do clean, compile, check, simple-release
  - yarn run expo-cli login -u ${EXP_USERNAME} -p ${EXP_PASSWORD} --non-interactive
  - yarn run expo-cli publish --release-channel ${TRAVIS_PULL_REQUEST_BRANCH}

notifications:
  email:
    on_success: always
